version: '3'

services:
  sb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb
    restart: always
    ports:
      - "80:80"
    tty: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user1:user1password@db:3306/game_db

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: game_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
